# Generated by Django 6.1 on 2026-08-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='idx_booking_user_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['parking', 'status'], name='idx_booking_parking_status'),
        ),
        migrations.AddIndex(
            model_name='parkinglocation',
            index=models.Index(fields=['city'], name='idx_loc_city'),
        ),
        migrations.AddIndex(
            model_name='parkinglocation',
            index=models.Index(fields=['city', 'status'], name='idx_loc_city_status'),
        ),
        migrations.AddIndex(
            model_name='parkingslot',
            index=models.Index(fields=['parking', 'status'], name='idx_slot_parking_status'),
        ),
        migrations.AddIndex(
            model_name='parkingslot',
            index=models.Index(fields=['slot_type', 'status'], name='idx_slot_type_status'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='idx_user_role'),
        ),
    ]
